kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-vpc-node-label-updater-role
  labels:
    app: ibm-vpc-block-csi-driver
    addonmanager.kubernetes.io/mode: Reconcile
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
